### ISSUE TITLE
can't seem to get it working

### ISSUE THREAD

**Issue by tobsn** [gorte/ST2-Whitespaces#1]
installed it over package manager - sublime v. 2217
do i need to switch something on?

**Comment by gorte** [comment]
I checked in this version. It's okay. Please describe the problem in detail. If you do not have such highlight colors as on the screenshot, then they are specified in the color scheme.

**Comment by tobsn** [comment]
after you install it with package manager, is there anything you have to activate? some settings maybe?

**Comment by karamfil** [comment]
Hello, 
I'm on Linux and can't get it working too.
Sublime v2.0.1 build 2217
I have also tried with the latest revision from git.

On windows it is fine - installed through the package manager.

@tobsn please do write better reports ;) i guess you are on linux too

**Comment by tobsn** [comment]
haha yeah, true, i mean its latest sublime on latest osx (ML GM). but i just assume that there is something missing. some setting in the theme settings etc.

**Comment by gorte** [comment]
Sorry, i forgot to set key bindings for Linux and OS X. Please, update package and test last changes.

**Comment by tobsn** [comment]
is there a way to set it on by default without key binding?
hitting super+alt+end seems a bit hard on a macbook... :)

**Comment by gorte** [comment]
Unfortunately there is no. But you set key bindings in your keymap file.
